name: Specify upstream version and Build Obfuscate BPB Panel

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      upstream_version:
        description: 'Specify upstream version to sync (e.g., v1.0.0 or 1.0.0)'
        required: false
        type: string
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: |
          npm install
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Fetch latest upstream release and worker.js
        id: fetch_upstream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPSTREAM_OWNER: lizhi123le
          UPSTREAM_REPO: BPB-Worker-Panel
          SPECIFIED_VERSION: ${{ github.event.inputs.upstream_version }}
        run: |
          set -euo pipefail

          if [ -n "$SPECIFIED_VERSION" ]; then
            # Use specified version
            echo "Using specified upstream version: $SPECIFIED_VERSION"
            RELEASE_INFO=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$UPSTREAM_OWNER/$UPSTREAM_REPO/releases/tags/$SPECIFIED_VERSION")
            RELEASE_TAG="$SPECIFIED_VERSION"
          else
            # Fallback to latest
            echo "No specified version; using latest upstream release"
            RELEASE_INFO=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$UPSTREAM_OWNER/$UPSTREAM_REPO/releases/latest")
            RELEASE_TAG=$(echo "$RELEASE_INFO" | jq -r '.tag_name // empty')
          fi

          echo "upstream_release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT

          DOWNLOAD_URL=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name=="worker.js") | .browser_download_url // empty')
          if [ -n "$DOWNLOAD_URL" ]; then
            echo "Found worker.js at $DOWNLOAD_URL, downloading..."
            wget -q -O origin.js "$DOWNLOAD_URL"
            echo "Downloaded origin.js size:" && ls -l origin.js || true
          else
            echo "No worker.js asset found in upstream release."
          fi

          # Pull upstream repo dev branch package.json (for version sync fallback)
          echo "Downloading upstream package.json (dev branch) for fallback"
          wget -q -O /tmp/upstream_package.json "https://raw.githubusercontent.com/$UPSTREAM_OWNER/$UPSTREAM_REPO/refs/heads/dev/package.json" || true
          if [ -f /tmp/upstream_package.json ]; then
            echo "upstream_package_json=true" >> $GITHUB_OUTPUT
            head -n 5 /tmp/upstream_package.json || true
          else
            echo "upstream_package_json=false" >> $GITHUB_OUTPUT
          fi

          # Download repo RELEASE.md (optional, from dev branch)
          if wget -q -O RELEASE.md "https://raw.githubusercontent.com/$UPSTREAM_OWNER/$UPSTREAM_REPO/refs/heads/dev/RELEASE.md" || true; then
            echo "RELEASE_md=true" >> $GITHUB_OUTPUT
          else
            echo "RELEASE_md=false" >> $GITHUB_OUTPUT
          fi

          # Determine if specified version is the latest (only if specified)
          if [ -n "$SPECIFIED_VERSION" ]; then
            LATEST_INFO=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$UPSTREAM_OWNER/$UPSTREAM_REPO/releases/latest")
            LATEST_TAG=$(echo "$LATEST_INFO" | jq -r '.tag_name // empty')
            NORMALIZED_SPECIFIED=$(echo "$SPECIFIED_VERSION" | sed 's/^v//')
            NORMALIZED_LATEST=$(echo "$LATEST_TAG" | sed 's/^v//')
            if [ "$NORMALIZED_SPECIFIED" = "$NORMALIZED_LATEST" ]; then
              echo "is_latest=true" >> $GITHUB_OUTPUT
            else
              echo "is_latest=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "is_latest=true" >> $GITHUB_OUTPUT
          fi

      - name: Extract upstream version
        id: extract_upstream_version
        env:
          SPECIFIED_VERSION: ${{ github.event.inputs.upstream_version }}
        run: |
          set -euo pipefail
          if [ -n "$SPECIFIED_VERSION" ]; then
            # Use specified version (strip 'v' prefix if present)
            UPVER=$(echo "$SPECIFIED_VERSION" | sed 's/^v//')
            echo "version=$UPVER" >> $GITHUB_OUTPUT
          elif [ -f /tmp/upstream_package.json ]; then
            VERSION=$(jq -r '.version // empty' /tmp/upstream_package.json)
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "version=" >> $GITHUB_OUTPUT
          fi

      - name: Sync package.json version (if found)
        run: |
          set -euo pipefail
          UPVER="${{ steps.extract_upstream_version.outputs.version }}"
          if [ -z "$UPVER" ]; then
            echo "No upstream version found; skipping package.json sync."
            exit 0
          fi

          # Backup and update package.json version field
          cp package.json package.json.bak
          jq --arg v "$UPVER" '.version = $v' package.json > package.json.tmp && mv package.json.tmp package.json

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: sync package.json version from upstream ($UPVER)" || echo "No version change to commit"
          git push || echo "Push failed (maybe no credential); continuing"

      - name: Get release version
        id: get_release_version
        run: echo "RELEASE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Build
        run: npm run build

      - name: Prepare release notes and collect artifacts
        id: prepare_artifacts
        run: |
          set -euo pipefail

          # Read RELEASE.md into output variable (URL-encode newlines)
          if [ -f RELEASE.md ]; then
            body=$(sed -e ':a' -e 'N' -e '$!ba' -e 's/%/%25/g' -e 's/\n/%0A/g' RELEASE.md)
            echo "RELEASE_BODY=$body" >> $GITHUB_OUTPUT
          else
            echo "RELEASE_BODY=" >> $GITHUB_OUTPUT
          fi

          # Ensure dist exists
          if [ ! -d dist ]; then
            echo "Error: dist directory not found. Build may have failed."
            ls -la
            exit 1
          fi

          # Prepare output dir and copy artifacts
          mkdir -p output
          shopt -s nullglob
          copied_files=()
          for f in dist/*; do
            cp -a "$f" output/ || { echo "Failed to copy $f"; ls -la dist; exit 1; }
            copied_files+=("$(basename "$f")")
          done
          shopt -u nullglob

          # Copy optional files if present
          [ -f origin.js ] && cp origin.js output/ || true
          [ -f RELEASE.md ] && cp RELEASE.md output/ || true
          if [ -f dist/_worker.js ]; then
            cp dist/_worker.js _worker.js || true
          fi

          # Build a safe, newline-separated list for output
          if [ -d output ]; then
            files_list=$(ls -1 output | sed -e ':a' -e 'N' -e '$!ba' -e 's/%/%25/g' -e 's/\n/%0A/g')
            echo "output_list=$files_list" >> $GITHUB_OUTPUT
          else
            echo "output_list=" >> $GITHUB_OUTPUT
          fi

      - name: Commit build artifacts back to repo
        if: |
          github.event_name != 'workflow_dispatch' ||
          steps.fetch_upstream.outputs.is_latest == 'true'
        env:
          GIT_AUTHOR_NAME: "github-actions[bot]"
          GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"
        run: |
          set -euo pipefail
          git status --porcelain --untracked-files=all || true

          # Stage artifacts (output dir and optional files)
          git add -A output || true
          [ -f _worker.js ] && git add _worker.js || true

          echo "Staged changes:"
          git --no-pager diff --cached --name-status || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git -c user.name="$GIT_AUTHOR_NAME" -c user.email="$GIT_AUTHOR_EMAIL" commit -m "chore(ci): add build artifacts from workflow"
            git push origin HEAD:main || echo "Push failed (check permissions)"
          fi

      - name: Upload Release Assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: output/*
          tag: v${{ env.RELEASE_VERSION }}
          release_name: Release v${{ env.RELEASE_VERSION }}
          overwrite: true
          file_glob: true
          prerelease: false
          body: ${{ steps.prepare_artifacts.outputs.RELEASE_BODY }}
